global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'priyankasushma13@gmail.com'
  smtp_auth_username: 'priyankasushma13@gmail.com'
  smtp_auth_password: 'qhco luqn qelz evjk'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'webhook'
  routes:
    - receiver: 'webhook'
      match:
        alertname: 'SomeSpecificAlert'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'priyankasushma13@gmail.com'
        send_resolved: true

  - name: 'webhook'
    webhook_configs:
      - url: 'http://192.168.43.218:5000/mywebhook'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
